# Generated by Django 6.0 on 2026-05-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='difficulty',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='module',
            name='phase_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='module',
            name='phase_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
