# Generated by Django 4.2.30 on 2026-05-03 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_difficulty_lesson_duration_module_phase_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignmentSubmission',
        ),
    ]
