# Generated by Django 4.2.11 on 2026-05-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_delete_assignmentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='codespaces_url',
            field=models.URLField(blank=True, help_text='Link to a GitHub Codespaces environment', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='replit_url',
            field=models.URLField(blank=True, help_text='Link to a Replit coding environment', max_length=500, null=True),
        ),
    ]
